packages:
  - packages/*
  - test/*

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  esbuild: false
  unrs-resolver: false
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@vitest/*'
  - vitest
