name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm run typecheck

  discover-test-suites:
    runs-on: ubuntu-latest
    outputs:
      suites: ${{ steps.suites.outputs.suites }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: List test suites
        id: suites
        run: echo "suites=$(ls test | jq --raw-input | jq --slurp --compact-output)" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ${{ matrix.os }}

    needs: [discover-test-suites]

    strategy:
      matrix:
        node: [22.x, 24.x, 26.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        suite: ${{ fromJSON(needs.discover-test-suites.outputs.suites) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Install playwright
        run: pnpm run prepare:playwright --with-deps

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm --filter ./test/${{ matrix.suite }} run test

  all-green:
    runs-on: ubuntu-slim
    timeout-minutes: 5

    if: always()
    needs: [lint, typecheck, test]

    steps:
      - name: Verify that all jobs succeeded
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: |
          echo 'Some jobs did not succeed: ${{ toJSON(needs) }}'
          exit 1
