name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [22.x, 24.x, 26.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Install playwright
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm run prepare:playwright --with-deps

      - name: Install playwright
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: pnpm run prepare:playwright

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

  all-green:
    runs-on: ubuntu-slim
    timeout-minutes: 5

    if: always()
    needs: [lint, typecheck, test]

    steps:
      - name: Verify that all jobs succeeded
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: |
          echo 'Some jobs did not succeed: ${{ toJSON(needs) }}'
          exit 1
